// <auto-generated />
using fp4me.Web.Data;
using fp4me.Web.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace fp4me.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20171206193318_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("fp4me.Web.Data.Models.Attraction", b =>
                {
                    b.Property<long>("AttractionID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<long?>("ParkID");

                    b.HasKey("AttractionID");

                    b.HasIndex("ParkID");

                    b.ToTable("Attractions");
                });

            modelBuilder.Entity("fp4me.Web.Data.Models.AttractionFastPassRequest", b =>
                {
                    b.Property<long>("AttractionFastPassRequestID")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("AttractionID");

                    b.Property<DateTime>("Date");

                    b.Property<int>("NumberOfPeople");

                    b.Property<int>("Status");

                    b.Property<long?>("UserID");

                    b.HasKey("AttractionFastPassRequestID");

                    b.HasIndex("AttractionID");

                    b.HasIndex("UserID");

                    b.ToTable("AttractionFastPassRequests");
                });

            modelBuilder.Entity("fp4me.Web.Data.Models.Park", b =>
                {
                    b.Property<long>("ParkID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abbreviation");

                    b.Property<string>("Name");

                    b.HasKey("ParkID");

                    b.ToTable("Parks");
                });

            modelBuilder.Entity("fp4me.Web.Data.Models.User", b =>
                {
                    b.Property<long>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccessToken");

                    b.Property<long>("SMSCredits");

                    b.Property<string>("SMSNotificationPhoneNumber");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("fp4me.Web.Data.Models.Attraction", b =>
                {
                    b.HasOne("fp4me.Web.Data.Models.Park", "Park")
                        .WithMany("Attractions")
                        .HasForeignKey("ParkID");
                });

            modelBuilder.Entity("fp4me.Web.Data.Models.AttractionFastPassRequest", b =>
                {
                    b.HasOne("fp4me.Web.Data.Models.Attraction", "Attraction")
                        .WithMany()
                        .HasForeignKey("AttractionID");

                    b.HasOne("fp4me.Web.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");
                });
#pragma warning restore 612, 618
        }
    }
}
